# Generated by Django 3.0.5 on 2020-05-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalmgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
